# Generated by Django 3.0.8 on 2020-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customanimal',
            name='farm',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm',
            field=models.ManyToManyField(through='core.Farmer', to='core.CustomAnimal'),
        ),
    ]
