# Generated by Django 3.0.8 on 2020-07-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200730_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customanimal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='core/audio'),
        ),
        migrations.AlterField(
            model_name='customanimal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='core/images'),
        ),
    ]
